/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Employee;

import Admin.Connector;
import Admin.Login;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Utkarsh
 */
public class Empdata extends javax.swing.JFrame {
      public static int id;
         public static String name;
         public static float sal,h,d,p,n;
         
         
         
    /**
     * Creates new form Empdata
     */
    public Empdata() {
        initComponents();
        showid.setText(""+Login.eid);
        print.setEnabled(false);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        pSlip = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        viewSlip = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        resetPass = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        logout = new javax.swing.JLabel();
        showid = new javax.swing.JLabel();
        mini = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        empid = new javax.swing.JTextField();
        empname = new javax.swing.JTextField();
        basicsal = new javax.swing.JTextField();
        hra = new javax.swing.JTextField();
        da = new javax.swing.JTextField();
        pf = new javax.swing.JTextField();
        netsal = new javax.swing.JTextField();
        load = new javax.swing.JButton();
        print = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 5));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 210, 2));

        pSlip.setBackground(new java.awt.Color(51, 51, 51));
        pSlip.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        pSlip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pSlipMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pSlipMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pSlipMouseExited(evt);
            }
        });
        pSlip.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PRINT SLIP");
        pSlip.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 40));

        jPanel2.add(pSlip, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 210, 60));

        viewSlip.setBackground(new java.awt.Color(102, 102, 102));
        viewSlip.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        viewSlip.setForeground(new java.awt.Color(51, 51, 51));
        viewSlip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewSlipMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewSlipMouseExited(evt);
            }
        });
        viewSlip.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SALARY SLIP");
        viewSlip.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 40));

        jPanel2.add(viewSlip, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 210, 60));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SALARY MANAGER");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EMPLOYEE ID :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        resetPass.setBackground(new java.awt.Color(51, 51, 51));
        resetPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        resetPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetPassMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resetPassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resetPassMouseExited(evt);
            }
        });
        resetPass.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("RESET PASSWORD");
        resetPass.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 40));

        jPanel2.add(resetPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 210, 60));

        jSeparator4.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 5));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 210, 3));

        logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logout.setForeground(new java.awt.Color(51, 153, 255));
        logout.setText("CLICK HERE TO LOGOUT");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jPanel2.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 490, -1, -1));

        showid.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        showid.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(showid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 50, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 540));

        mini.setBackground(new java.awt.Color(204, 204, 204));
        mini.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mini.setForeground(new java.awt.Color(51, 153, 255));
        mini.setText("  -");
        mini.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        mini.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miniMouseExited(evt);
            }
        });
        jPanel1.add(mini, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 40, 30));

        exit.setBackground(new java.awt.Color(255, 0, 51));
        exit.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 0, 51));
        exit.setText("   X");
        exit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 43, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("SALARY SLIP"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Emp ID                                    :");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 190, -1));

        jLabel8.setText("Basic Salary                             :");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 190, -1));

        jLabel9.setText("HRA                                        :");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 145, 180, -1));

        jLabel10.setText("Name                                      :");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 75, 170, -1));

        jLabel11.setText("DA                                          :");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 180, 200, -1));

        jLabel12.setText("PF                                           :");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 215, 200, -1));

        jLabel13.setText("NET SALARY                           :");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 247, 200, 20));

        empid.setEditable(false);
        empid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empidActionPerformed(evt);
            }
        });
        jPanel4.add(empid, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 37, 190, -1));

        empname.setEditable(false);
        jPanel4.add(empname, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 72, 190, -1));

        basicsal.setEditable(false);
        jPanel4.add(basicsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 107, 190, -1));

        hra.setEditable(false);
        jPanel4.add(hra, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 142, 190, -1));

        da.setEditable(false);
        jPanel4.add(da, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 177, 190, -1));

        pf.setEditable(false);
        jPanel4.add(pf, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 212, 190, -1));

        netsal.setEditable(false);
        jPanel4.add(netsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 247, 190, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 480, 300));

        load.setBackground(new java.awt.Color(51, 51, 51));
        load.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        load.setForeground(new java.awt.Color(255, 255, 255));
        load.setText("LOAD");
        load.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadActionPerformed(evt);
            }
        });
        jPanel3.add(load, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 95, 43));

        print.setBackground(new java.awt.Color(51, 51, 51));
        print.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        print.setForeground(new java.awt.Color(255, 255, 255));
        print.setText("PRINT");
        print.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel3.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 94, 42));

        jPanel5.setBackground(new java.awt.Color(51, 153, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("YOUR SALARY SLIP");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 550, 40));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 550, 4));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 532, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pSlipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pSlipMouseClicked
        Printdata p=new Printdata();
        p.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_pSlipMouseClicked

    private void pSlipMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pSlipMouseEntered
        pSlip.setBackground(new Color(102,102,102)); // TODO add your handling code here:
    }//GEN-LAST:event_pSlipMouseEntered

    private void pSlipMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pSlipMouseExited
       pSlip.setBackground(new Color(51,51,51)); // TODO add your handling code here:
    }//GEN-LAST:event_pSlipMouseExited

    private void viewSlipMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewSlipMouseEntered
         // adData.setBackground(new Color(102,102,102));         // TODO add your handling code here:
    }//GEN-LAST:event_viewSlipMouseEntered

    private void viewSlipMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewSlipMouseExited
        // adData.setBackground(new Color(51,51,51)); // TODO add your handling code here:
    }//GEN-LAST:event_viewSlipMouseExited

    private void resetPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetPassMouseClicked
        Resetpass rp=new Resetpass();
        rp.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_resetPassMouseClicked

    private void resetPassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetPassMouseEntered
        resetPass.setBackground(new Color(102,102,102)); // TODO add your handling code here:
    }//GEN-LAST:event_resetPassMouseEntered

    private void resetPassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetPassMouseExited
        resetPass.setBackground(new Color(51,51,51)); // TODO add your handling code here:
    }//GEN-LAST:event_resetPassMouseExited

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        new Login().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_logoutMouseClicked

    private void miniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseClicked
        this.setState(JFrame.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_miniMouseClicked

    private void miniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseEntered

        mini.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
    }//GEN-LAST:event_miniMouseEntered

    private void miniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseExited

        mini.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204,204,204)));
    }//GEN-LAST:event_miniMouseExited

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exit.setBackground(Color.red);
        exit.setForeground(Color.red);
        exit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,0,0)));// TODO add your handling code here:
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        exit.setForeground(Color.red);
        exit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204,204,204)));// TODO add your handling code here:
    }//GEN-LAST:event_exitMouseExited

    private void empidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empidActionPerformed

    private void loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadActionPerformed
        try{
                Connector con=new Connector();
                Statement stmt=con.getConnection().createStatement();
                
                String qry="SELECT * FROM EMPDATA WHERE empno="+Login.eid+";";
                ResultSet rs = stmt.executeQuery(qry);
                if(rs.next())
                {
                    id=rs.getInt("empno");
                    name=rs.getString("ename");
                    sal=rs.getFloat("basic");
                    h=rs.getFloat("hra");
                    d=rs.getFloat("da");
                    p=rs.getFloat("pf");
                    n=rs.getFloat("net");
                    empid.setText(""+id);
                    empname.setText(rs.getString("ename"));
                    basicsal.setText(""+rs.getFloat("basic"));
                    hra.setText(""+rs.getFloat("hra"));
                    da.setText(""+rs.getFloat("da"));
                    pf.setText(""+rs.getFloat("pf"));
                    netsal.setText(""+rs.getFloat("net"));
                    pSlip.setEnabled(true);
                    print.setEnabled(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Something went wrong");
                }
            

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error in Connectivity");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_loadActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        new Printdata().setVisible(true);
        //     this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empdata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField basicsal;
    private javax.swing.JTextField da;
    private javax.swing.JTextField empid;
    private javax.swing.JTextField empname;
    private javax.swing.JLabel exit;
    private javax.swing.JTextField hra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton load;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel mini;
    private javax.swing.JTextField netsal;
    private javax.swing.JPanel pSlip;
    private javax.swing.JTextField pf;
    private javax.swing.JButton print;
    private javax.swing.JPanel resetPass;
    private javax.swing.JLabel showid;
    private javax.swing.JPanel viewSlip;
    // End of variables declaration//GEN-END:variables
}
