/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Employee;

import Admin.Connector;
import Admin.Login;
import java.awt.Color;
import java.sql.Statement;
import javax.swing.JFrame;

/**
 *
 * @author Utkarsh
 */
public class Resetpass extends javax.swing.JFrame {

    /**
     * Creates new form Resetpass
     */
    public Resetpass() {
        initComponents();
        showid.setText(""+Login.eid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        pSlip = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        viewSlip = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        resetPass = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        logout = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        showid = new javax.swing.JLabel();
        mini = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        npass = new javax.swing.JTextField();
        cpass = new javax.swing.JTextField();
        opass = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        error = new javax.swing.JLabel();
        error1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 5));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 210, 2));

        pSlip.setBackground(new java.awt.Color(51, 51, 51));
        pSlip.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        pSlip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pSlipMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pSlipMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pSlipMouseExited(evt);
            }
        });
        pSlip.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PRINT SLIP");
        pSlip.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 40));

        jPanel2.add(pSlip, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 210, 60));

        viewSlip.setBackground(new java.awt.Color(51, 51, 51));
        viewSlip.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        viewSlip.setForeground(new java.awt.Color(51, 51, 51));
        viewSlip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewSlipMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewSlipMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewSlipMouseExited(evt);
            }
        });
        viewSlip.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SALARY SLIP");
        viewSlip.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 40));

        jPanel2.add(viewSlip, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 210, 60));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SALARY MANAGER");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        resetPass.setBackground(new java.awt.Color(102, 102, 102));
        resetPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        resetPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetPassMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resetPassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resetPassMouseExited(evt);
            }
        });
        resetPass.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("RESET PASSWORD");
        resetPass.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 40));

        jPanel2.add(resetPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 210, 60));

        jSeparator4.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 5));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 210, 3));

        logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logout.setForeground(new java.awt.Color(51, 153, 255));
        logout.setText("CLICK HERE TO LOGOUT");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jPanel2.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 490, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EMPLOYEE ID :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        showid.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        showid.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(showid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 50, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 540));

        mini.setBackground(new java.awt.Color(204, 204, 204));
        mini.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mini.setForeground(new java.awt.Color(51, 153, 255));
        mini.setText("  -");
        mini.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        mini.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miniMouseExited(evt);
            }
        });
        jPanel1.add(mini, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 40, 30));

        exit.setBackground(new java.awt.Color(255, 0, 51));
        exit.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 0, 51));
        exit.setText("   X");
        exit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 43, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("OLD PASSWORD                       :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 180, 20));

        jLabel7.setText("NEW PASSWORD                      :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 200, 20));

        jLabel8.setText("CONFIRM PASSWORD              :");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 180, 20));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("RESET");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 100, 40));

        npass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(npass, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 200, 25));

        cpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(cpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 200, 25));

        opass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(opass, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 200, 25));

        jPanel5.setBackground(new java.awt.Color(51, 153, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("      RESET PASSWORD");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 550, 40));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 550, 4));

        error.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        error.setForeground(new java.awt.Color(255, 51, 51));
        jPanel3.add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 230, 30));

        error1.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        error1.setForeground(new java.awt.Color(255, 51, 51));
        jPanel3.add(error1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 220, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 532, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pSlipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pSlipMouseClicked
        Printdata p=new Printdata();
        p.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_pSlipMouseClicked

    private void pSlipMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pSlipMouseEntered
        pSlip.setBackground(new Color(102,102,102)); // TODO add your handling code here:
    }//GEN-LAST:event_pSlipMouseEntered

    private void pSlipMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pSlipMouseExited
        pSlip.setBackground(new Color(51,51,51));// TODO add your handling code here:
    }//GEN-LAST:event_pSlipMouseExited

    private void viewSlipMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewSlipMouseEntered
       viewSlip.setBackground(new Color(102,102,102)); // adData.setBackground(new Color(102,102,102));         // TODO add your handling code here:
    }//GEN-LAST:event_viewSlipMouseEntered

    private void viewSlipMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewSlipMouseExited
        viewSlip.setBackground(new Color(51,51,51));// adData.setBackground(new Color(51,51,51)); // TODO add your handling code here:
    }//GEN-LAST:event_viewSlipMouseExited

    private void resetPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetPassMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_resetPassMouseClicked

    private void resetPassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetPassMouseEntered
         // TODO add your handling code here:
    }//GEN-LAST:event_resetPassMouseEntered

    private void resetPassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetPassMouseExited
         // TODO add your handling code here:
    }//GEN-LAST:event_resetPassMouseExited

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        new Login().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_logoutMouseClicked

    private void miniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseClicked
        this.setState(JFrame.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_miniMouseClicked

    private void miniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseEntered

        mini.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
    }//GEN-LAST:event_miniMouseEntered

    private void miniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseExited

        mini.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204,204,204)));
    }//GEN-LAST:event_miniMouseExited

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exit.setBackground(Color.red);
        exit.setForeground(Color.red);
        exit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,0,0)));// TODO add your handling code here:
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        exit.setForeground(Color.red);
        exit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204,204,204)));// TODO add your handling code here:
    }//GEN-LAST:event_exitMouseExited

    private void viewSlipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewSlipMouseClicked
         Empdata ed=new Empdata();
        ed.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_viewSlipMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{     
                int emp=Login.eid;
                String op=opass.getText();
                String np=npass.getText();
                String cp=cpass.getText();
                
                if(np.equals(cp)){
                    
                Connector con=new Connector();
                Statement stmt=con.getConnection().createStatement();
                
                String qry="update emplogin set emp_pass='"+np+"' where emp_id="+emp+" && emp_pass='"+op+"';";
                stmt.executeUpdate(qry);
                error.setText("PASSWORD UPDATED SUCCESSFULLY !");
                
                npass.setText("");
                opass.setText("");
                cpass.setText("");
                error1.setText("");
                }
                else{
                    
                    error1.setText("PASSWORD NOT MATCH !");
                    
                }
        }
        catch(Exception e){
            
            error.setText("SOMETHING WENT WRONG !");
            
        }
           // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resetpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resetpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resetpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resetpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resetpass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cpass;
    private javax.swing.JLabel error;
    private javax.swing.JLabel error1;
    private javax.swing.JLabel exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel mini;
    private javax.swing.JTextField npass;
    private javax.swing.JTextField opass;
    private javax.swing.JPanel pSlip;
    private javax.swing.JPanel resetPass;
    private javax.swing.JLabel showid;
    private javax.swing.JPanel viewSlip;
    // End of variables declaration//GEN-END:variables
}
