/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;
package Assets;

import Employee.Empdata;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Utkarsh
 */
public class Login extends javax.swing.JFrame {
    public static int i=1;
    public static String name;
    public static int eid;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
         images();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mini = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        invalid = new javax.swing.JLabel();
        js1 = new javax.swing.JSeparator();
        js2 = new javax.swing.JSeparator();
        loginad = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        loginemp = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(513, 480));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 5, 480));

        jPanel1.setBackground(new java.awt.Color(9, 132, 227));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("HERE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, 60));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("MANAGE");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, 60));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("YOUR");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, 60));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("SALARY");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, 60));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 170, 2));

        jSeparator4.setForeground(new java.awt.Color(102, 204, 255));
        jSeparator4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 170, 2));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 480));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 34)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGIN");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 1, 140, 48));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 420, 50));

        userid.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        userid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        userid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                useridMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                useridMouseExited(evt);
            }
        });
        userid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useridActionPerformed(evt);
            }
        });
        jPanel3.add(userid, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 230, 30));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setText("EMPLOYEE ID  :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        mini.setBackground(new java.awt.Color(204, 204, 204));
        mini.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mini.setForeground(new java.awt.Color(9, 132, 227));
        mini.setText("  -");
        mini.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        mini.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miniMouseExited(evt);
            }
        });
        jPanel3.add(mini, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 40, 30));

        exit.setBackground(new java.awt.Color(255, 0, 51));
        exit.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 0, 51));
        exit.setText("   X");
        exit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        jPanel3.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 43, 30));

        invalid.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        invalid.setForeground(new java.awt.Color(255, 51, 51));
        jPanel3.add(invalid, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 300, 230, 30));

        js1.setForeground(new java.awt.Color(102, 204, 255));
        js1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 5));
        jPanel3.add(js1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 230, 3));

        js2.setForeground(new java.awt.Color(102, 204, 255));
        js2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 5));
        jPanel3.add(js2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 230, 3));

        loginad.setBackground(new java.awt.Color(51, 51, 51));
        loginad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginadMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LOGIN");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("AS");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("  ADMIN");

        javax.swing.GroupLayout loginadLayout = new javax.swing.GroupLayout(loginad);
        loginad.setLayout(loginadLayout);
        loginadLayout.setHorizontalGroup(
            loginadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginadLayout.createSequentialGroup()
                .addGroup(loginadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginadLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(loginadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginadLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel6))
                            .addComponent(jLabel2)))
                    .addGroup(loginadLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        loginadLayout.setVerticalGroup(
            loginadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginadLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(loginad, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 100, 80));

        loginemp.setBackground(new java.awt.Color(51, 51, 51));
        loginemp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginempMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginempMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginempMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(" LOGIN");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" AS");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(" EMPLOYEE");

        javax.swing.GroupLayout loginempLayout = new javax.swing.GroupLayout(loginemp);
        loginemp.setLayout(loginempLayout);
        loginempLayout.setHorizontalGroup(
            loginempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginempLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(loginempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginempLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9))
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginempLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        loginempLayout.setVerticalGroup(
            loginempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginempLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(loginemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 100, 80));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setText("PASSWORD :");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        pass.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        pass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                passMouseExited(evt);
            }
        });
        jPanel3.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 230, 30));

        jPanel5.setBackground(new java.awt.Color(9, 132, 227));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 104, 350, 10));
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 30, 50));
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 40, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 513, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     private void images()
     {
         ImageIcon icon=new ImageIcon("D:\\Java\\Netbeans Workspace\\SalaryManager\\src\\main\\java\\Assets\\user_32.png");
         ImageIcon icon1=new ImageIcon("D:\\Java\\Netbeans Workspace\\SalaryManager\\src\\main\\java\\Assets\\password_32.png");
          jLabel14.setIcon(icon);
          jLabel15.setIcon(icon1);

     }
    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exit.setBackground(Color.red);
        exit.setForeground(Color.red);   
        exit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,0,0)));// TODO add your handling code here:
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
      System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
      exit.setForeground(Color.RED);   
      exit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204,204,204)));// TODO add your handling code here:
    }//GEN-LAST:event_exitMouseExited

    private void miniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseEntered

      mini.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(9,132,227)));
    }//GEN-LAST:event_miniMouseEntered

    private void miniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseExited

       mini.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204,204,204)));
    }//GEN-LAST:event_miniMouseExited

    private void miniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseClicked
     this.setState(JFrame.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_miniMouseClicked

    private void useridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useridActionPerformed

    private void useridMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_useridMouseEntered
     js1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(9,132,227),3)); 
     // TODO add your handling code here:
    }//GEN-LAST:event_useridMouseEntered

    private void useridMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_useridMouseExited
      js1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51,51,51),3));       // TODO add your handling code here:
    }//GEN-LAST:event_useridMouseExited

    private void passMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passMouseEntered
       js2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(9,132,227),3)); // TODO add your handling code here:
    }//GEN-LAST:event_passMouseEntered

    private void passMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passMouseExited
       js2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51,51,51),3)); // TODO add your handling code here:
    }//GEN-LAST:event_passMouseExited

    private void loginadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginadMouseEntered
        loginad.setBackground(new Color(102,102,102));      // TODO add your handling code here:
    }//GEN-LAST:event_loginadMouseEntered

    private void loginadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginadMouseExited
         loginad.setBackground(new Color(51,51,51));  // TODO add your handling code here:
    }//GEN-LAST:event_loginadMouseExited

    private void loginempMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginempMouseEntered
      loginemp.setBackground(new Color(102,102,102));   // TODO add your handling code here:
    }//GEN-LAST:event_loginempMouseEntered

    private void loginempMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginempMouseExited
       loginemp.setBackground(new Color(51,51,51));  // TODO add your handling code here:
    }//GEN-LAST:event_loginempMouseExited

    private void loginadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginadMouseClicked
        try
            {
                Connector con=new Connector();
                Statement stmt=con.getConnection().createStatement();
                String Adno=userid.getText().toUpperCase();
                String Pass=pass.getText();

                String qry="Select * from admin;";
                ResultSet rs=stmt.executeQuery(qry);
                while(rs.next())
                {
                    String id=rs.getString("admin_id");
                    String p=rs.getString("admin_pass");
                    
                    if(Adno.equals(id))
                            {
                              if(Pass.equals(p))
                              {
                                 name=rs.getString("admin_name");
                               
                                 MainMenu m=new MainMenu();
                                         m.setVisible(true);
                                  this.dispose();
                                  
                              }
                              else
                              {
                                  invalid.setText("INVALID ADMIN ID OR PASSWORD !");
                              }
                            }
                    else
                    {
                        invalid.setText("INVALID ADMIN ID OR PASSWORD ! ");
                    }
                }
            }
            catch(Exception e)
            {
                invalid.setText("SOMETHING WENT WRONG !");
            }// TODO add your handling code here:
    }//GEN-LAST:event_loginadMouseClicked

    private void loginempMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginempMouseClicked
        try
            {
                Connector con=new Connector();
                Statement stmt=con.getConnection().createStatement();
                String empid=userid.getText(); 
                String Pass=pass.getText();
                
                if(empid.length()==0||Pass.length()==0)
                {
                    invalid.setText("ENTER EMPLOYEE ID OR PASSWORD !");
                }
                
                int empno=Integer.parseInt(empid);
                
                String qry="Select * from emplogin;";
                ResultSet rs=stmt.executeQuery(qry);
                while(rs.next())
                {
                    int id=rs.getInt("emp_id");
                    String p=rs.getString("emp_pass");
                    
                    if(id==empno)
                            {
                              if(Pass.equals(p))
                              {
                                 eid=rs.getInt("emp_id");
                                 Empdata m=new Empdata();
                                 m.setVisible(true);
                                 this.dispose();
                                  
                              }
                              else
                              {
                                  invalid.setText("INVALID PASSWORD !");
                              }
                            }
                    else
                    {
                        invalid.setText("INVALID EMPLOYEE ID ! ");
                    }
                }
            }
            catch(Exception e)
            {
                invalid.setText("ENTER EMPLOYEE ID !");
            }
       // TODO add your handling code here:
    }//GEN-LAST:event_loginempMouseClicked
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit;
    private javax.swing.JLabel invalid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator js1;
    private javax.swing.JSeparator js2;
    private javax.swing.JPanel loginad;
    private javax.swing.JPanel loginemp;
    private javax.swing.JLabel mini;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField userid;
    // End of variables declaration//GEN-END:variables
}
