/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;
package Assets;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Utkarsh
 */
public class MainMenu extends javax.swing.JFrame {
     
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        
      
        initComponents(); 
//        ImageIcon ic=new ImageIcon(ClassLoader.getSystemResource("Admin/Assets/addition_32.png"));
//        er.setIcon(ic);
        welcome.setText(""+Login.name.toUpperCase());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        resetPass = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        modData = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        adData = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        er = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        delData = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        viewData = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        logout = new javax.swing.JLabel();
        mini = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        empid = new javax.swing.JTextField();
        empname = new javax.swing.JTextField();
        basicsal = new javax.swing.JTextField();
        hra = new javax.swing.JTextField();
        da = new javax.swing.JTextField();
        pf = new javax.swing.JTextField();
        netsal = new javax.swing.JTextField();
        ls = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 5));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 210, 2));

        resetPass.setBackground(new java.awt.Color(51, 51, 51));
        resetPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        resetPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetPassMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                resetPassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                resetPassMouseExited(evt);
            }
        });
        resetPass.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RESET PASSWORD");
        resetPass.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 40));

        jPanel2.add(resetPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 210, 60));

        modData.setBackground(new java.awt.Color(51, 51, 51));
        modData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        modData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modDataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modDataMouseExited(evt);
            }
        });
        modData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("UPDATE RECORD");
        modData.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 40));

        jPanel2.add(modData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 210, 60));

        adData.setBackground(new java.awt.Color(102, 102, 102));
        adData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        adData.setForeground(new java.awt.Color(51, 51, 51));
        adData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adDataMouseExited(evt);
            }
        });
        adData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ENTER RECORD");
        adData.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 40));
        adData.add(er, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 30, 20));

        jPanel2.add(adData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 210, 60));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SALARY MANAGER");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        welcome.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        welcome.setForeground(new java.awt.Color(255, 255, 255));
        welcome.setText("WELCOME  ADMIN ");
        jPanel2.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        delData.setBackground(new java.awt.Color(51, 51, 51));
        delData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        delData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delDataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                delDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                delDataMouseExited(evt);
            }
        });
        delData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DELETE RECORD");
        delData.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 40));

        jPanel2.add(delData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 210, 60));

        viewData.setBackground(new java.awt.Color(51, 51, 51));
        viewData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        viewData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewDataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewDataMouseExited(evt);
            }
        });
        viewData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("VIEW RECORD");
        viewData.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 140, 40));

        jPanel2.add(viewData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 210, 60));

        jSeparator4.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 5));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 210, 3));

        logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logout.setForeground(new java.awt.Color(51, 153, 255));
        logout.setText("CLICK HERE TO LOGOUT");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jPanel2.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 490, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 540));

        mini.setBackground(new java.awt.Color(204, 204, 204));
        mini.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mini.setForeground(new java.awt.Color(51, 153, 255));
        mini.setText("  -");
        mini.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        mini.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miniMouseExited(evt);
            }
        });
        jPanel1.add(mini, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 40, 30));

        exit.setBackground(new java.awt.Color(255, 0, 51));
        exit.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 0, 51));
        exit.setText("   X");
        exit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 43, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(5, 406));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Employee ID                             :");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 200, 20));

        jLabel10.setText("Employee Name                       :");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 200, 20));

        jLabel11.setText("Basic Salary                               :");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 200, 20));

        jLabel12.setText("DA                                            :");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 200, 20));

        jLabel13.setText("HRA                                          :");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 200, 20));

        jLabel14.setText("PF                                             :");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 200, 20));

        jLabel15.setText("NET SALARY                             :");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 200, 20));

        save.setBackground(new java.awt.Color(51, 51, 51));
        save.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("SAVE");
        save.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel3.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 100, 40));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("ADD NEW");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 100, 40));

        empid.setEditable(false);
        empid.setForeground(new java.awt.Color(153, 153, 153));
        empid.setText("         Generated Automatically");
        empid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        empid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empidActionPerformed(evt);
            }
        });
        jPanel3.add(empid, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 200, 25));

        empname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        empname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empnameActionPerformed(evt);
            }
        });
        jPanel3.add(empname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 200, 25));

        basicsal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(basicsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 200, 25));

        hra.setEditable(false);
        hra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(hra, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 200, 25));

        da.setEditable(false);
        da.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        da.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daActionPerformed(evt);
            }
        });
        jPanel3.add(da, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 200, 25));

        pf.setEditable(false);
        pf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.add(pf, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 200, 25));

        netsal.setEditable(false);
        netsal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        netsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netsalActionPerformed(evt);
            }
        });
        jPanel3.add(netsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 200, 25));

        ls.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jPanel3.add(ls, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 190, 40));

        jPanel5.setBackground(new java.awt.Color(51, 153, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel19.setText("ADD EMPLOYEE DATA");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 550, 40));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 74, 550, 4));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 532, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseClicked
        this.setState(JFrame.ICONIFIED);        
    }//GEN-LAST:event_miniMouseClicked

    private void miniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseEntered

        mini.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
    }//GEN-LAST:event_miniMouseEntered

    private void miniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseExited

        mini.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204,204,204)));
    }//GEN-LAST:event_miniMouseExited

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        exit.setBackground(Color.red);
        exit.setForeground(Color.red);
        exit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,0,0)));// TODO add your handling code here:
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        exit.setForeground(Color.red);
        exit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204,204,204)));// TODO add your handling code here:
    }//GEN-LAST:event_exitMouseExited

    private void adDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adDataMouseEntered
       // adData.setBackground(new Color(102,102,102));         // TODO add your handling code here:
    }//GEN-LAST:event_adDataMouseEntered

    private void adDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adDataMouseExited
       // adData.setBackground(new Color(51,51,51)); // TODO add your handling code here:
    }//GEN-LAST:event_adDataMouseExited

    private void modDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modDataMouseEntered
       modData.setBackground(new Color(102,102,102)); // TODO add your handling code here:
    }//GEN-LAST:event_modDataMouseEntered

    private void modDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modDataMouseExited
        modData.setBackground(new Color(51,51,51));// TODO add your handling code here:
    }//GEN-LAST:event_modDataMouseExited

    private void resetPassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetPassMouseEntered
        resetPass.setBackground(new Color(102,102,102));// TODO add your handling code here:
    }//GEN-LAST:event_resetPassMouseEntered

    private void resetPassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetPassMouseExited
        resetPass.setBackground(new Color(51,51,51));// TODO add your handling code here:
    }//GEN-LAST:event_resetPassMouseExited

    private void delDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delDataMouseEntered
       delData.setBackground(new Color(102,102,102)); // TODO add your handling code here:
    }//GEN-LAST:event_delDataMouseEntered

    private void delDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delDataMouseExited
       delData.setBackground(new Color(51,51,51)); // TODO add your handling code here:
    }//GEN-LAST:event_delDataMouseExited

    private void viewDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewDataMouseEntered
       viewData.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_viewDataMouseEntered

    private void viewDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewDataMouseExited
        viewData.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_viewDataMouseExited

    private void resetPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetPassMouseClicked
        Reset r=new Reset();
        r.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_resetPassMouseClicked

    private void modDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modDataMouseClicked
        Update up=new Update();
         up.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_modDataMouseClicked

    private void delDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delDataMouseClicked
         Delete del=new Delete();
         del.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_delDataMouseClicked

    private void viewDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewDataMouseClicked
         View v=new View();
         v.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_viewDataMouseClicked

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        try{
            
            Connector con=new Connector();
               
            Statement stmt=con.getConnection().createStatement();
            Statement stmt1=con.getConnection().createStatement();
            
            double b=Double.parseDouble(basicsal.getText());
            String name=empname.getText();
            String pa="employe@123";
            
            
            
            double h,d,p,n;
            h=0.3*b;
            d=0.1*b;
            p=0.05*b;
            n=b+h+d-p;
            hra.setText(""+h);
            da.setText(""+d);
            pf.setText(""+p);
            netsal.setText(""+n);
            
            String sql="insert into empdata(ename,basic,hra,da,pf,net) values("+"'"+name+"'"+","+b+","+h+","+d+","+p+","+n+")";           
            String sql1="select empno from empdata where ename='"+name+"';";
            stmt.executeUpdate(sql);
            ResultSet rs=stmt.executeQuery(sql1);
            
            int eno=0;
            if(rs.next())
            {
            eno=rs.getInt("empno");
            empid.setText(""+eno);
            }
   
            String sql2="insert into emplogin values("+eno+","+"'"+pa+"'"+");";
            stmt1.executeUpdate(sql2);
            JOptionPane.showMessageDialog(null, "Adding Records in Employee Table");
            stmt1.close();
            stmt.close();
                      
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,""+e);
        }
        
    }//GEN-LAST:event_saveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        empid.setText("         Generated Automatically");
        empname.setText("");
        basicsal.setText("");
        hra.setText("");
        da.setText("");
        pf.setText("");
        netsal.setText("");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void empnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empnameActionPerformed

    private void netsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netsalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_netsalActionPerformed

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
       new Login().setVisible(true);
       this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_logoutMouseClicked

    private void daActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daActionPerformed

    private void empidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
                MainMenu m=new MainMenu();
                m.setVisible(true);
                        
 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adData;
    private javax.swing.JTextField basicsal;
    private javax.swing.JTextField da;
    private javax.swing.JPanel delData;
    private javax.swing.JTextField empid;
    private javax.swing.JTextField empname;
    private javax.swing.JLabel er;
    private javax.swing.JLabel exit;
    private javax.swing.JTextField hra;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel ls;
    private javax.swing.JLabel mini;
    private javax.swing.JPanel modData;
    private javax.swing.JTextField netsal;
    private javax.swing.JTextField pf;
    private javax.swing.JPanel resetPass;
    private javax.swing.JButton save;
    private javax.swing.JPanel viewData;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
