/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;
package Assets;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Utkarsh
 */
public class StartPage extends javax.swing.JFrame {

    /**
     * Creates new form StartPage
     */
    public StartPage() {
        initComponents();
        images();
//        setIcon();
//   ImageIcon ic=new ImageIcon(ClassLoader.getSystemResource("/Assets/businessman-g005c32395_1280.png"));
//     Image img1=new ImageIcon(this.getClass().getResource("/Assets/businessman-g005c32395_1280.png")).getImage();
//          this.setIconImage(img1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void images()
    {
        ImageIcon icon=new ImageIcon("D:\\Java\\Netbeans Workspace\\SalaryManager\\src\\main\\java\\Assets\\skyscraper-g99069cc9f_1280.png");
        Image im=icon.getImage();
        Image imgScale =im.getScaledInstance(img.getWidth(),img.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledIcon=new ImageIcon(imgScale);
        img.setIcon(scaledIcon);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt1 = new javax.swing.JLabel();
        txt2 = new javax.swing.JLabel();
        Loading = new javax.swing.JProgressBar();
        jPanel3 = new javax.swing.JPanel();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SALARY MANAGER");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 380, 40));

        txt1.setFont(new java.awt.Font("NSimSun", 0, 10)); // NOI18N
        txt1.setForeground(new java.awt.Color(255, 255, 255));
        txt1.setText("Loading....");
        jPanel2.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 20));

        txt2.setFont(new java.awt.Font("NSimSun", 0, 10)); // NOI18N
        txt2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 20, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 550, 90));

        Loading.setFocusable(false);
        jPanel1.add(Loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 280, 570, 10));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 570, 320));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 290));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       StartPage sp=new StartPage();
       sp.setVisible(true);
       Login log=new Login();
       try{
           for(int i=0;i<=100;i++)
           {
               Thread.sleep(100);
               sp.txt2.setText(i+"%");
               sp.Loading.setValue(i);
               if(i==10)
               {
                   sp.txt1.setText("Turning On Modules....");
               }
               if(i==20)
               {
                   sp.txt1.setText("Loading Modules....");
               }
               if(i==50)
               {
                   sp.txt1.setText("Connecting to Database....");
               }
               if(i==70)
               {
                   sp.txt1.setText("Connection Successfull !");
               }
               if(i==80)
               {
                   sp.txt1.setText("Launching Application....");
               }
           }
       } catch(Exception e)
                   {
                   }
                   
                   sp.setVisible(false);
                   log.setVisible(true);
                   sp.dispose();
                   
                   
      
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new StartPage().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Loading;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt2;
    // End of variables declaration//GEN-END:variables

//    private void setIcon() {
//       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("businessman-g005c32395_1280.png")));
//    }
}
